spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wizshopjava
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: teamsparta
    password: 1234
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: validate

  data:
    redis:
      host: localhost
      port: 6379

jwt:
  access-token-secret-key: "abcdefgabcdefgabcdefgabcdefgabcdefgabcdefgabcdefg"
  access-token-expires-in: "1800000"